language: python
python:
  - "3.8.5"
install:
  - pip install coveralls
script:
  - python3 creditCard.py < test1.txt
  - python3 creditCard.py < test2.txt
  - python3 creditCard.py < test3.txt
after_success:
  - coveralls